apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fastify-boilerplate
  annotations:
    circleci.com/project-slug: ronabet/fastify-boilerplate
    backstage.io/code-coverage: scm-only
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: guests
